### ISSUE TITLE
バルーンにしている時の挙動

### ISSUE THREAD

**Issue by kkk30** [anoyetta/RINGS#22]
チャットで発言があると勝手にバルーンが解除されウィンドウが展開する動作はやめてほしい。
意図的にバルーンにしているので手動で解除するまではバルーンのままでお願いしたい。

**Comment by anoyetta** [comment]
バルーンとはなんでしょうか？

**Comment by kkk30** [comment]
“バルーン”といっていたのは、RINGSのログウィンドウを最小化した際にでるコメントのようなアイコンのことを言っているつもりでした。
（バルーンの意味がそもそも間違っていたのは申し訳ありませんでした）
