### ISSUE TITLE
キャラクター名にハイフンがあるキャラはゲーム内からチャットを送信出来ない？

### ISSUE THREAD

**Issue by akidevolive** [anoyetta/RINGS#23]
お世話になっております。

知人からバグ登録をお願いされて代筆しています。
知人がRINGSを使用させて頂こうとして以下の様な問題が発生しました。

【事象】
RINGSアプリのホーム画面からのチャットは上手くDiscordのサーバ側へ送信されているが
ゲーム内からのチャットはDiscordサーバへ送信されない

【その他】
色々と幾つか試して以下の様な事がわかりました。
知人の名前は「Abc Def-ghij」の様な間にハイフンが入る形式なのです。
チャットリンク設定でも上記の名前で入力してあります。
ですが、ホームのStatus欄のPlayerの所では「Abc Def-Ghij」という形で
ハイフンの後が大文字に変換されていました。

上記に気づき、知人に別キャラで再度RINGSを設定してもらいました。
別キャラの名前は「Abc Defghij」という今度はハイフン無しの名前でした。

こちらのキャラからは問題無くゲーム内のチャットからもDiscordサーバ側へチャットの内容が
送信されました。

この事から、ハイフン入りの名前の場合、その直後の文字が大文字に変換されてしまい
本人が発言したチャットと認識されていないのではと考えています。

ご確認頂けますでしょうか。

よろしくお願いします。

**Comment by anoyetta** [comment]
確認はしていませんが [v1.2.1.2810-Stable](https://github.com/anoyetta/RINGS/releases/tag/v1.2.1.2810-Stable) で直してみました。
確認してください。

**Comment by akidevolive** [comment]
お世話になっております、早々のご対応ありがとうございます。

当事者の知人がまだログイン出来る状況ではなかったので
こちらで以下の様なキャラ名のキャラを作成して動作を確認したのですが
発言を拾うことは出来ていませんでした。

【キャラ名】
Hoge Rings-che

以下に現状を記載しておきます。

①RINGSのバージョン
RINGS - v1.2.1.2810

②Statusの状態
　Sharlayan　　　　→ Attached
　Player　　　　　 → Hoge Rings-Che(WAR)
　Active Profile　　→ Hoge Rings-che [FIXED] - LS1
　DISCORD Bot　　→ Ready

③チャットリンク設定で紐付けたLSへゲーム内から発言した場合
　・自身のチャットオーバーレイへは発言が表示されている
　・自身のRINGSアプリのChat Logへは発言が表示されている
　・紐付けているDiscord側のチャンネルへは発言が表示されていない
　・他のメンバーのチャットオーバーレイへは発言が表示されていない

④RINGSアプリ内のチャット欄からの発言
　・自身のチャットオーバーレイへ発言が表示されている
　・紐付けているDiscord側のチャンネルへ発言が表示されている
　・他のメンバーのチャットオーバーレイへ発言が表示されている

**Comment by anoyetta** [comment]
修正箇所が漏れていたので更に修正しました。
ご確認ください。

**Comment by akidevolive** [comment]
お世話になっております。

先ほど上記で報告させて頂いたキャラで無事
発言が拾われる事を確認致しました。

早々のご対応感謝します。
ありがとうございました！

**Comment by anoyetta** [comment]
それはなにより。
