### ISSUE TITLE
チャットのログがたまるとタブ切り替え時に重くなる

### ISSUE THREAD

**Issue by SeeLog** [anoyetta/RINGS#26]
あるタブのチャットがそれなりに貯まると，他のタブに切り替わってからまたログのたまったタブに切り替わる際に動作が重くなります．

具体的には一旦黒い文字でチャットが描画されてから本来のチャットの色で描画され直すなどしています．
タブを切り替えるたびにレンダリングしないようにするなどの方法は取れないでしょうか？

あるいは以下の作戦も考えられます．

- 一定時間を過ぎたチャットログは消去するようにする
- チャットをクリアする機能を作る

以上です．ご検討の程をよろしくお願いいたします．

**Comment by anoyetta** [comment]
何かしら対策を入れます。
以前から見られる現象ではあります。そして一度対策を入れて当初よりかはましになってはいます。

以前に対策を講じたときには再レンダリングしないようにするのは困難もしくは今の仕組み上無理だということで諦めた記憶があります。かなり前のことなので記憶が曖昧ですが。

記憶を辿りつつ再検討してみますが、一定時間より前のチャットログは描画しないという処理にする可能性が高いかと思います。
